### ISSUE TITLE
filter add error- application did not respond

### ISSUE THREAD

**Issue by pseuflare** [stephanlensky/hyacinth#37]
When trying to add any filters, the filter never gets created and gets the error "The application did not respond".  

```
/filter add title rule_type and rule test 
/filter add body rule_type and rule test
``` 

The search is running and is pulling in facebook marketplace items in the log.

**Comment by pseuflare** [comment]
```
Traceback (most recent call last): 
File "/app/hyacinth/util/decorators . py", line 15, in wrapper 
return await wrapped(*args, **kwargs) 
File "/app/hyacinth/discord/discord_bot . py", line 150, in add 
await create_filter(self, interaction, field, Rule Type(rule_type), rule) 
File "/app/hyacinth/discord/commands/filter.py", line 55, in create_filter 
validate_filter_expr(notifier, field, rule_expr) 
File "/app/hyacinth/discord/commands/filter.py", line 33, in validate_filter_expr 
targets_numerical_field 
any( 
File "/app/hyacinth/discord/commands/filter. py", line 34, in <genexpr> 
targeted_field . type _ in (int, float) for targeted_field in targeted_fields 
AttributeError: 'Fieldlnfo' object has no attribute 'type

```

**Comment by stephanlensky** [comment]
Thanks for the report, should be fixed now.
