### ISSUE TITLE
FB Marketplace plugin fails to search

### ISSUE THREAD

**Issue by malone-c** [stephanlensky/hyacinth#38]
Service times out while searching FB Marketplace. In particular, the program times out when executing this line in the FB Marketplace plugin:

```
await page.waitForFunction(
    """document.querySelector("div[aria-label='Collection of Marketplace items']") !== null""",
)
```

This is presumably because the Browserless instance is not authenticated, so it sees the login page instead of the search results. Therefore, no HTML element with the selector `aria-label='Collection of Marketplace items'` ever shows up.

I understand that you might not want to support FB authentication directly, but it might be good to handle this error explicitly. 

<details><summary>Full logs</summary>
<p>

```
hyacinth-service-1      | 2023-08-09 12:58:56 [6] [DEBUG] hyacinth.monitor Polling search SearchSpec(id=1, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='melbourne' category='lamps') since 2023-08-09 06:58:56.056317+00:00
hyacinth-browserless-1  | 2023-08-09T12:58:56.063Z browserless:job HQZIV3LD2UUFM8YH33Q3RO8J7L2B5CR0: /?stealth&blockAds=true: Inbound WebSocket request.
hyacinth-browserless-1  | 2023-08-09T12:58:56.065Z browserless:hardware Checking overload status: CPU 1% Memory 10%
hyacinth-browserless-1  | 2023-08-09T12:58:56.067Z browserless:job HQZIV3LD2UUFM8YH33Q3RO8J7L2B5CR0: Adding new job to queue.
hyacinth-browserless-1  | 2023-08-09T12:58:56.067Z browserless:server Starting new job
hyacinth-browserless-1  | 2023-08-09T12:58:56.067Z browserless:system Generating fresh chrome browser
hyacinth-browserless-1  | 2023-08-09T12:58:56.067Z browserless:job HQZIV3LD2UUFM8YH33Q3RO8J7L2B5CR0: Getting browser.
hyacinth-browserless-1  | 2023-08-09T12:58:56.069Z browserless:chrome-helper Launching Chrome with args: {
hyacinth-browserless-1  |   "args": [
hyacinth-browserless-1  |     "--no-sandbox",
hyacinth-browserless-1  |     "--enable-logging",
hyacinth-browserless-1  |     "--v1=1",
hyacinth-browserless-1  |     "--disable-dev-shm-usage",
hyacinth-browserless-1  |     "--no-first-run",
hyacinth-browserless-1  |     "--remote-debugging-port=46267",
hyacinth-browserless-1  |     "--user-data-dir=/tmp/browserless-data-dir-z8XiRS"
hyacinth-browserless-1  |   ],
hyacinth-browserless-1  |   "blockAds": true,
hyacinth-browserless-1  |   "dumpio": false,
hyacinth-browserless-1  |   "headless": false,
hyacinth-browserless-1  |   "stealth": true,
hyacinth-browserless-1  |   "ignoreDefaultArgs": false,
hyacinth-browserless-1  |   "ignoreHTTPSErrors": false,
hyacinth-browserless-1  |   "pauseOnConnect": false,
hyacinth-browserless-1  |   "playwright": false,
hyacinth-browserless-1  |   "userDataDir": "/tmp/browserless-data-dir-z8XiRS",
hyacinth-browserless-1  |   "meta": {
hyacinth-browserless-1  |     "protocol": null,
hyacinth-browserless-1  |     "slashes": null,
hyacinth-browserless-1  |     "auth": null,
hyacinth-browserless-1  |     "host": null,
hyacinth-browserless-1  |     "port": null,
hyacinth-browserless-1  |     "hostname": null,
hyacinth-browserless-1  |     "hash": null,
hyacinth-browserless-1  |     "search": "?stealth&blockAds=true",
hyacinth-browserless-1  |     "query": {
hyacinth-browserless-1  |       "stealth": "",
hyacinth-browserless-1  |       "blockAds": "true"
hyacinth-browserless-1  |     },
hyacinth-browserless-1  |     "pathname": "/",
hyacinth-browserless-1  |     "path": "/?stealth&blockAds=true",
hyacinth-browserless-1  |     "href": "/?stealth&blockAds=true"
hyacinth-browserless-1  |   },
hyacinth-browserless-1  |   "executablePath": "/usr/bin/google-chrome",
hyacinth-browserless-1  |   "handleSIGINT": false,
hyacinth-browserless-1  |   "handleSIGTERM": false,
hyacinth-browserless-1  |   "handleSIGHUP": false
hyacinth-browserless-1  | }
hyacinth-browserless-1  | 2023-08-09T12:58:56.491Z browserless:chrome-helper Chrome PID: 21497
hyacinth-browserless-1  | 2023-08-09T12:58:56.491Z browserless:chrome-helper Finding prior pages
hyacinth-browserless-1  | 2023-08-09T12:58:56.699Z browserless:chrome-helper Found 1 pages
hyacinth-browserless-1  | 2023-08-09T12:58:56.699Z browserless:chrome-helper Setting up page Unknown
hyacinth-browserless-1  | 2023-08-09T12:58:56.699Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
hyacinth-browserless-1  | 2023-08-09T12:58:56.699Z browserless:system Chrome launched 632ms
hyacinth-browserless-1  | 2023-08-09T12:58:56.699Z browserless:system Got chrome instance
hyacinth-browserless-1  | 2023-08-09T12:58:56.700Z browserless:job HQZIV3LD2UUFM8YH33Q3RO8J7L2B5CR0: Starting session.
hyacinth-browserless-1  | 2023-08-09T12:58:56.700Z browserless:job HQZIV3LD2UUFM8YH33Q3RO8J7L2B5CR0: Proxying request to /devtools/browser route: ws://127.0.0.1:46267/devtools/browser/e9450f8a-9be0-4d14-9a95-7f39b9604050.
hyacinth-browserless-1  | 2023-08-09T12:58:56.701Z browserless:chrome-helper Setting up file:// protocol request rejection
hyacinth-browserless-1  | 2023-08-09T12:58:56.701Z browserless:chrome-helper Setting up page for ad-blocking
hyacinth-browserless-1  | 2023-08-09T12:58:56.758Z browserless:chrome-helper Setting up page Unknown
hyacinth-browserless-1  | 2023-08-09T12:58:56.758Z browserless:chrome-helper Injecting download dir "/usr/src/app/workspace"
hyacinth-browserless-1  | 2023-08-09T12:58:56.760Z browserless:chrome-helper Setting up file:// protocol request rejection
hyacinth-browserless-1  | 2023-08-09T12:58:56.760Z browserless:chrome-helper Setting up page for ad-blocking
hyacinth-service-1      | 2023-08-09 12:58:56 [6] [DEBUG] plugins.marketplace.client Loading marketplace search results
hyacinth-service-1      | 2023-08-09 12:58:56 [6] [DEBUG] hyacinth.util.scraping Loading page https://www.facebook.com/marketplace/melbourne/lamps/?sortBy=creation_time_descend&exact=false
hyacinth-service-1      | 2023-08-09 12:58:57 [6] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
hyacinth-service-1      | Job "MarketplaceMonitor.poll_search (trigger: interval[0:10:00], next run at: 2023-08-09 13:08:56 UTC)" raised an exception
hyacinth-service-1      | Traceback (most recent call last):
hyacinth-service-1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.11/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
hyacinth-service-1      |     retval = await job.func(*job.args, **job.kwargs)
hyacinth-service-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1      |   File "/app/hyacinth/monitor.py", line 81, in poll_search
hyacinth-service-1      |     listings: list[BaseListing] = await search_spec.plugin.get_listings(
hyacinth-service-1      |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1      |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
hyacinth-service-1      |     return await get_listings(search_params, after_time, limit)
hyacinth-service-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hyacinth-service-1      |   File "/app/plugins/marketplace/client.py", line 25, in get_listings
hyacinth-service-1      |     async for listing in search:
hyacinth-service-1      |   File "/app/plugins/marketplace/client.py", line 50, in _search
hyacinth-service-1      |     await page.waitForFunction(
hyacinth-service-1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.11/lib/python3.11/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
hyacinth-service-1      |     raise result
hyacinth-service-1      | pyppeteer.errors.TimeoutError: Waiting for function failed: timeout 30000ms exceeds.
```

</p>
</details>

**Comment by stephanlensky** [comment]
Hm, I didn't know marketplace ever required authentication to search. Do you know if this is a rate-limiting thing? I was able to complete searches in my tests, but I only ever tried with a single search at a time.

**Comment by stephanlensky** [comment]
Interesting, I can access that search results page (https://www.facebook.com/marketplace/melbourne/lamps/?sortBy=creation_time_descend&exact=false) without logging in here on US east coast, but since I noticed the search was for Melbourne, I tried a VPN to Australia and got the login page.

I am hesitant to add authentication for this case, just because if user accounts are detected as web scrapers they will probably get banned pretty fast. The error should definitely be handled better though, I'll add it to my list.

**Comment by malone-c** [comment]
Well spotted, thanks for pointing that out. In that case, it looks like it will be hard to run this on the cloud -- I will need to either authenticate or route my requests through a VPN on my home router. But it sounds like that's just the nature of FB scraping.
