### ISSUE TITLE
Discord notifications very slow

### ISSUE THREAD

**Issue by Andreww9** [stephanlensky/hyacinth#77]
I am running hyacinth from my home desktop.  I am currently using VS code along with docker.  I have attached a picture of my searches and filters within discord.  The issue I have is I am getting notifications hours after something new is posted.  From my understanding hyacinth is searching marketplace every 10 minutes, and I have set discord to check those results every 60 seconds.  At this point it seems that marketplace may not even be producing any results (even though I know there are new postings that would fall into my search parameters). Bellow is my most recent log file (poll failure).  Any help would be greatly appreciated!  Side note, the computer is running a core i5 7th gen 8gb ram, and standard disk drive.  It is not very fast and can be slow at times.  But it is still running VS code and docker.  Not sure if the computer speed has an impact on the issue I am having?

Traceback (most recent call last):
  File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
    listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/craigslist/plugin.py", line 38, in get_listings
    return await get_listings(search_params, after_time, limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/craigslist/client.py", line 33, in get_listings
    async for listing in search:
  File "/app/plugins/craigslist/client.py", line 63, in _search
    detail_content = await _get_detail_content(browser_page, result_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/plugins/craigslist/client.py", line 105, in _get_detail_content
    await browser_page.wait_for_selector("section.body")
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 8329, in wait_for_selector
    await self._impl_obj.wait_for_selector(
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_page.py", line 357, in wait_for_selector
    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 327, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

Picture of search parameters:

![Capture](https://github.com/stephanlensky/hyacinth/assets/11082515/284da77b-7574-45ce-a8e2-84ddce53b7ed)

**Comment by JrVega03** [comment]
Thats what I am getting too... any update?

**Comment by edisonmamani176-source** [comment]
encontre una aplicacion que hace lo mismo con mas funcionalidades talvez te sirva "https://firupost.netlify.app/docs" espero te ayude
